# Generated by Django 3.0.7 on 2021-01-19 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='emenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_name', models.CharField(max_length=50)),
                ('dish_name', models.CharField(max_length=50, null=True)),
                ('dish_description', models.CharField(max_length=500, null=True)),
            ],
        ),
    ]
