# Generated by Django 3.0.7 on 2021-01-19 13:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('eMenu', '0002_auto_20210119_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emenu',
            name='dish_add_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='emenu',
            name='dish_update_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
