# Generated by Django 3.0.7 on 2021-01-19 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eMenu', '0003_auto_20210119_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emenu',
            name='dish_add_time',
            field=models.DateTimeField(default='2021-01-19 15:01:12'),
        ),
    ]
