# Generated by Django 3.0.7 on 2021-01-20 07:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('eMenu', '0004_auto_20210119_1601'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nazwa menu')),
                ('description', models.CharField(max_length=500, null=True)),
                ('price', models.CharField(max_length=50)),
                ('preparation_time', models.CharField(max_length=50)),
                ('add_time', models.DateTimeField(default='2021-01-20 07:04:58')),
                ('update_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('dish_wege', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='emenu',
        ),
    ]
