# Generated by Django 3.0.7 on 2021-01-20 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eMenu', '0007_auto_20210120_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='add_time',
            field=models.DateTimeField(default='2021-01-20 11:16:58', verbose_name='Data dodania menu'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='add_time',
            field=models.DateTimeField(default='2021-01-20 11:16:58', verbose_name='Data dodania przep.'),
        ),
        migrations.CreateModel(
            name='CardItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card', to='eMenu.Card')),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dish', to='eMenu.Dish')),
            ],
            options={
                'managed': True,
            },
        ),
    ]
