# Generated by Django 3.0.7 on 2021-01-20 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eMenu', '0012_auto_20210120_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='add_time',
            field=models.DateTimeField(default='2021-01-20 19:47:08', verbose_name='Data dodania przep.'),
        ),
    ]
