# Generated by Django 3.0.7 on 2021-01-20 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eMenu', '0013_auto_20210120_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='add_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data dodania przep.'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='preparation_time',
            field=models.IntegerField(verbose_name='Przygotowanie (min)'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cena (zł)'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='update_time',
            field=models.DateTimeField(auto_now=True, verbose_name='Data zmiany przepisu'),
        ),
    ]
