# Generated by Django 3.0.7 on 2021-01-20 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eMenu', '0014_auto_20210120_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='wege',
            field=models.BooleanField(default=True, verbose_name='Wegetariańskie'),
        ),
    ]
