# Generated by Django 3.0.7 on 2021-01-20 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eMenu', '0015_auto_20210120_2125'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carditems',
            options={},
        ),
    ]
