# Generated by Django 3.0.7 on 2021-01-21 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eMenu', '0016_auto_20210120_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/', verbose_name='Obrazek'),
        ),
    ]
