# Generated by Django 3.0.7 on 2021-01-31 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eMenu', '0017_auto_20210121_1648'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='card',
            options={},
        ),
    ]
